services:

  stream-gateway-api:
    build: ./StreamGateway/
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - default

  chat-service-api:
    build: ./ChatService/
    ports:
      - "8081:8081"
    depends_on:
      - chat-service-db
      - kafka
    networks:
      - default

  analytics-service-api:
    build: ./AnalyticsService/
    ports:
      - "8082:8082"
    depends_on:
      - analytics-service-db
      - kafka
    networks:
      - default

  moderation-service-api:
    build: ./ModerationService/
    ports:
      - "8083:8083"
    depends_on:
      - moderation-service-db
      - kafka
    networks:
      - default

  notification-service-api:
    build: ./NotificationService/
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    networks:
      - default

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092" 
      - "9093:9093"
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9094,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CLUSTER_ID=my-kafka-cluster
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - default

  chat-service-db:
    hostname: chat-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - default

  analytics-service-db:
    hostname: analytics-db
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - default

  moderation-service-db:
    hostname: moderation-db
    image: mongo
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - default

volumes:
  kafka_data:

networks:
  default:
    driver: bridge
    name: amnis-network
